### ISSUE TITLE
How to set TextField type "password" ?

### ISSUE THREAD

**Issue by cloudshill** [aforemny/material-components-elm#28]
textFieldConfig
                  | label = "Password"
                  , outlined = True
                  , additionalAttributes =  [ Html.Attributes.type_ "password" ]
that's invalid !

**Comment by aforemny** [comment]
Hi @cloudshill, thank you for reporting this! It is indeed not currently possible to set `type "password"` for Textfields, because `additionalAttributes` are applied to the wrapping custom element and not the underlying `input` element.

Other attributes like this are (ie. `value`) are mapped in the configuration so that they can get passed to the `input`. I am not quite sure if we would add a field

- `password : Bool`,
- `type : String`, or
- `nativeControl : List (Html.Attribute msg)`

to `TextFieldConfig`. I will investigate what types are there besides `password`, and then add support for that.

**Comment by aforemny** [comment]
Hi @cloudshill,

I have investigated a bit and I have added a `type_ : String` configuration field to `TextFieldConfig` (104be35183ebc0cac297d4056c8220dfee9bf527).

You should this be able to write

    textField { textFieldConfig | type = "password" }

If there are issues with this still, or anything remains unclear feel free to re-open! Thanks again for reporting this issue.

**Comment by cloudshill** [comment]
thanks.
